### ISSUE TITLE
Ecran MKS TFT35

### ISSUE THREAD

**Issue by Soowarez** [tititopher68-dev/Marlin#30]
Bonjour,
j'aimerais savoir s'il étais possible de mettre votre firmware (ecran) sur un écran MKS tft35 de mon Ender 3 v2 ?

Si pas possible je dois réinstaller mon écran d'origine ? 

Merci

**Comment by tititopher68-dev** [comment]
@Soowarez 
Hélas non on ne peut pas utiliser un écran MKS.

**Comment by ADQS-FR** [comment]
Pas de problème, merci

**Comment by Soowarez** [comment]
D'accord, merci
